dependencies:
  - gitdb                     4.0.11
  - GitPython                 3.1.43
  - mysql-connector-python    8.4.0
  - numpy                     1.26.4
  - pandas                    2.2.2
  - streamlit                 1.37.0
  - streamlit-navigation-bar  3.3.0
  - streamlit-option-menu     0.3.13
  - urllib3                   2.2.1
